name: daps-final-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.0
  - pip
  - Cython>=0.22
  - pystan>=2.14
  - numpy>=1.10.0
  - pandas>=0.23.4
  - matplotlib>=2.0.0
  - LunarCalendar>=0.0.9
  - convertdate>=2.1.2
  - holidays>=0.9.5
  - setuptools-git>=1.2
  - python-dateutil>=2.8.0
  - tqdm>=4.36.1
  - scikit-learn
  - plotly
  - scipy
  - fbprophet
  - pip:
      - nltk
      - pymongo
      - seaborn
      - quandl
      - yfinance == 0.1.87
      - pandas_datareader
      - alpaca_trade_api
